import '../globals.css'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

interface LayoutProps {
  children: ReactNode;
}


export const metadata: Metadata = {
  title: 'timetable',
  description: 'Generated by Toucan',
}

export default function Layout(props:LayoutProps){
  return(
    <div>
      {props.children}
    </div>
  )
}

